namespace Nancy.Bootstrapper.Mef
{

    public interface INancyGeneratedPartMetadataView
    {

        /// <summary>
        /// Gets whether or not the export was auto generated.
        /// </summary>
        bool[] AutoGenerated { get; }

    }

}
